services:
  web:
    image: php:8.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306
    volumes:
      - "db_data:/var/lib/mysql"

volumes:
  db_data:
